### ISSUE TITLE
@bytemd/vue支持vue3

### ISSUE THREAD

**Issue by guixiaobai** [pd4d10/hashmd#157] opened 2022-03-24 07:27 UTC
@bytemd/vue支持vue3 。
引入相关依赖就报错了

**Comment by pd4d10** [comment] 2022-03-27 07:55
Duplicate of #77

**Closed as completed by pd4d10** 2022-03-27 07:55 UTC

**Comment by pd4d10** [comment] 2022-03-31 08:17
`@bytemd/vue-next` has been published to support Vue3.
