### ISSUE TITLE
generated structure(toc) with code in heading

### ISSUE THREAD

**Issue by PassionPenguin** [pd4d10/hashmd#68] opened 2021-03-22 18:04 UTC
```markdown
### `go run`
## `go run`
# `go run`
```
<img width="1255" alt="Screenshot 2021-03-23 at 2 04 15 AM" src="https://user-images.githubusercontent.com/41184947/112036860-146faa00-8b7c-11eb-8bc0-4b8a2a16c7e2.png">

**Comment by PassionPenguin** [comment] 2021-03-22 18:07
see https://github.com/bytedance/bytemd/blob/master/packages/bytemd/src/toc.svelte#L31

**Comment by pd4d10** [comment] 2021-04-02 07:42
Duplicate of #48

**Closed as completed by pd4d10** 2021-04-02 07:42 UTC
