### ISSUE TITLE
@icon-park/svg 依赖体积太大，怎么减少体积剔除无用图标

### ISSUE THREAD

**Issue by kong0102** [pd4d10/hashmd#243] opened 2022-12-20 07:42 UTC
![image](https://user-images.githubusercontent.com/23163591/208610720-1f955ab7-2645-4f9d-81b4-5d37ecf4b827.png)

**Comment by pd4d10** [comment] 2023-01-03 11:10
Duplicate of #228

**Closed as completed by pd4d10** 2023-01-03 11:10 UTC
