### ISSUE TITLE
Cannot use in SvelteKit

### ISSUE THREAD

**Issue by Manuelbaun** [pd4d10/hashmd#139] opened 2021-12-17 20:21 UTC
Hi Guys, 

your bytemd looks very cool and I like to use it in a SvelteKit project. Unfortunately I cannot make it work. I get that error :
```
The requested module '/node_modules/.pnpm/rehype-raw@5.1.0/node_modules/rehype-raw/index.js?v=5165e040' does not provide an export named 'default'
SyntaxError: The requested module '/node_modules/.pnpm/rehype-raw@5.1.0/node_modules/rehype-raw/index.js?v=5165e040' does not provide an export named 'default'
```

Any idea how to resolve that. I tried the suggested setup.

```html
<script>
  import { Editor, Viewer } from 'bytemd';
  import gfm from '@bytemd/plugin-gfm';

  let value;
  const plugins = [
    gfm(),
    // Add more plugins here
  ];

  function handleChange(e) {
    value = e.detail.value;
  }
</script>

<template>
  <Editor {value} {plugins} on:change={handleChange} />
</template>
```

**Comment by codart1** [comment] 2022-02-13 15:48
I got the same issue

**Comment by benmccann** [comment] 2022-02-26 03:48
Duplicate of https://github.com/bytedance/bytemd/issues/96

**Comment by kotx** [comment] 2022-02-26 03:57
> Duplicate of #96

Are you sure this is the same issue? The error messages are slightly different.

**Comment by benmccann** [comment] 2022-03-01 16:44
There's a few different issues involved. I posted a summary on the other issue. See here: https://github.com/bytedance/bytemd/issues/96#issuecomment-1054538106

**Comment by pd4d10** [comment] 2022-03-26 10:30
Duplicate of #96 

Let's track it there

**Closed as completed by pd4d10** 2022-03-26 10:30 UTC
