### ISSUE TITLE
使用@bytemd/plugin-mermaid 时，报错

### ISSUE THREAD

**Issue by snail-boy** [pd4d10/hashmd#208] opened 2022-07-07 02:09 UTC
<img width="709" alt="image" src="https://user-images.githubusercontent.com/34472552/177674878-1a225170-80d9-47a7-ab34-607f2c44531e.png">

WARN: Could not find the language 'mermaid', did you forget to load/include a language module

v1.17.0版本

**Comment by pd4d10** [comment] 2022-07-08 12:02
Duplicate of #185

**Closed as completed by pd4d10** 2022-07-08 12:02 UTC
